FROM node:20.2-alpine3.17

RUN npm config set registry https://registry.npmjs.org/

ARG BUILD_CONTEXT

# Set environment variables
ENV NODE_ENV ${NODE_ENV}
ENV API_PORT ${API_PORT}
ENV API_LOG_LEVEL ${API_LOG_LEVEL}
ENV API_X_API_KEY ${API_X_API_KEY}
ENV EXTERNAL_API_URL ${EXTERNAL_API_URL}
ENV EXTERNAL_API_USERS_ENDPOINT ${EXTERNAL_API_USERS_ENDPOINT}
ENV EXTERNAL_API_ALBUMS_ENDPOINT ${EXTERNAL_API_ALBUMS_ENDPOINT}
ENV EXTERNAL_API_PHOTOS_ENDPOINT ${EXTERNAL_API_PHOTOS_ENDPOINT}
ENV LOCAL_CACHE_ENABLED ${LOCAL_CACHE_ENABLED}
ENV LOCAL_CACHE_TTL ${LOCAL_CACHE_TTL}
ENV LOCAL_CACHE_PATH ${LOCAL_CACHE_PATH}


WORKDIR /base
COPY ./packages/$BUILD_CONTEXT packages/$BUILD_CONTEXT

WORKDIR /base/packages/$BUILD_CONTEXT
RUN npm build


EXPOSE ${NODE_ENV}

CMD ["npm", "run", "start:prod"]
